rob1_base:
  x: 0
  y: -0.7331
  z: 0
  roll: 0
  pitch: 0
  yaw: 1.57079632679

rob2_base:
  x: 0
  y: 0.7331
  z: 0
  roll: 0
  pitch: 0
  yaw: -1.57079632679

whiteboard:
  x: 0
  y: 0
  z: -0.125
  roll: 0
  pitch: 0
  yaw: 0
